cart/urls.py
from django.urls import path

from .views import cart_remove, cart_add, cart_detail

app_name = 'cart'
urlpatterns = [
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('', cart_detail, name='cart_detail'),
]

cupons/urls.py
from django.urls import path

from .views import cupon_aplly

app_name = 'cupon'
urlpatterns = [
    path('apply/', cupon_aplly, name='aplly'),
]

django_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('cupons/', include('cupons.urls', namespace='cupons')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from .views import (
    order_create,
    admin_order_detail,
    admin_order_pdf,
)

app_name = 'orders'
urlpatterns = [
    path('create/', order_create, name='order_create'),
    path('admin/order/<int:order_id>/', admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', admin_order_pdf, name='admin_order_pdf'),
]

shop/urls.py
from django.urls import path

from shop.views import product_list, product_detail

app_name = 'shop'
urlpatterns = [
    path('<slug:category_slug>/', product_list, name='product_list_category'),
    path('<int:product_id>/<slug:slug>/', product_detail, name='product_detail'),
    path('', product_list, name='product_list'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from cupons.forms import CuponApllyForm
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            update_quantity=cd['update'],
        )
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'update': True,
        })
    cupon_aplly_form = CuponApllyForm()
    context = {
        'cart': cart,
        'cupon_aplly_form': cupon_aplly_form,
    }
    return render(request, 'cart/cart_detail.html', context)

templates/cart/cart_detail.html
{% extends 'shop/base.html' %}
{% block title %}
    Ваша корзина товаров
{% endblock %}
{% block content %}
    <h1>Ваша корзина товаров</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Продукт</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Полная цена</th>
            <th>Цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="


                                    {% if product.image %}{{ product.image.url }}{% else %} http://dummyimage.com/300 {% endif %}"
                                 class="img-responsive">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>
                        <form action="{% url 'cart:cart_add' product.id %}" method="post" class="add">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            {% csrf_token %}
                            <button type="submit">Обновить</button>
                        </form>
                    </td>
                    <td><a href="{% url "cart:cart_remove" product.id %}">Удалить</a></td>
                    <td class="num">{{ item.price }} руб.</td>
                    <td class="num">{{ item.total_price }} руб.</td>
                </tr>
            {% endwith %}
        {% endfor %}
        {% if cart.cupon %}
            <tr class="subtotal">
                <td>Сумма без скидки</td>
                <td colspan="4"></td>
                <td>{{ cart.get_total_price }}</td>
            </tr>
            <tr>
                <td>"{{ cart.cupon.code }}" купон на ({{ cart.cupon.discount }} % ниже)</td>
                <td colspan="4"></td>
                <td class="num discount">- {{ cart.get_discount|floatformat:'0' }} руб.</td>
            </tr>
        {% endif %}
        <tr class="total">
            <td>Всего</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price_after_discount|floatformat:'0' }} руб.</td>
        </tr>
        </tbody>
    </table>
    <p>Купон</p>
    <form action="{% url 'cupon:aplly' %}" method="post" class="add">
        {% csrf_token %}
        {{ cupon_aplly_form }}
        <button type="submit">Применить</button>
    </form>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="btn">Продолжить Шопинг</a>
        <a href="{% url 'orders:order_create' %}" class="btn">Оформить заказ</a>
    </p>
{% endblock %}