cart/urls.py
from django.urls import path

from .views import cart_remove, cart_add, cart_detail

app_name = 'cart'
urlpatterns = [
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('', cart_detail, name='cart_detail'),
]

django_shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django_shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('orders.urls', namespace='orders')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('cupons/', include('cupons.urls', namespace='cupons')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from shop.views import product_list, product_detail

app_name = 'shop'
urlpatterns = [
    path('<slug:category_slug>/', product_list, name='product_list_category'),
    path('<int:product_id>/<slug:slug>/', product_detail, name='product_detail'),
    path('', product_list, name='product_list'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['-name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products', verbose_name='Категория')
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name='Изображение товара')
    description = models.TextField(blank=True, verbose_name='Описание')
    price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='Цена')
    stock = models.BooleanField(default=True, verbose_name='На складе')
    available = models.BooleanField(default=True, verbose_name='Доступен')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлён')

    class Meta:
        ordering = ['-name']
        index_together = [
            ['id', 'slug']
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import get_object_or_404, render

from cart.forms import CartAddProductForm
from .models import Category, Product


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {
        'category': category,
        'categories': categories,
        'products': products,
    }
    return render(request, 'shop/product_list.html', context)


def product_detail(request, product_id, slug):
    product = get_object_or_404(Product, id=product_id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    context = {
        'product': product,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'shop/product_detail.html', context)

templates/shop/base.html
<!doctype html>
{% load staticfiles bootstrap3 %}
<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Styles -->
    {% bootstrap_css %}
    {#    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">#}
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link rel="stylesheet" href="{% static 'css/ie10-viewport-bug-workaround.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700&amp;subset=cyrillic" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<section id="header">
    <div class="top container">
        Мой Онлайн-Магазин
    </div>
    <div class="top-bl">
        <div class="container">
            <div class="cart">
                {% with total_items=cart|length %}
                    {% if cart|length > 0 %}
                        Ваша корзина:
                        <a href="{% url 'cart:cart_detail' %}">
                            {{ total_items }} тов. {{ cart.get_total_price }} руб.
                        </a>
                    {% else %}
                        Корзина пустая
                    {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
</section>
<section id="content row" class="container">
    {% block content %}{% endblock %}
</section>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static '/js/jquery.min.js' %}"><\/script>')</script>
{% bootstrap_javascript %}
{#<script src="/static/js/bootstrap.js"></script>#}
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>

templates/shop/product_detail.html
{% extends "shop/base.html" %}
{% load staticfiles bootstrap3 %}
{% block title %}
    {{ product.name }}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <div class="col-sm-4">
            <img src="{% if product.image %}{{ product.image.url }}{% else %} http://dummyimage.com/300 {% endif %}"
                 class="img-responsive">
        </div>
        <div class="col-sm-8">
            <h1>{{ product.name }}</h1>
            <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
            <p class="price">{{ product.price }} руб.</p>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <button type="submit">Добавить в корзину</button>
            </form>
            <span>{{ product.description | linebreaks }}</span>
        </div>
    </div>
{% endblock %}

templates/shop/product_list.html
{% extends 'shop/base.html' %}
{% load staticfiles bootstrap3 %}
{% block title %}
    {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar" class="col-sm-3">
        <h3>Категории</h3>
        <ul>
            <li {% if not category %} class="selected" {% endif %}>
                <a href="{% url "shop:product_list" %}">Все</a>
            </li>
            {% for cat in categories %}
                <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
                    <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product_list col-sm-9">
        <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
        <div class="items row">
            {% for product in products %}
                <div class="item col-sm-4">
                    <a href="{{ product.get_absolute_url }}">
                        <img class="img-responsive" src="
                                {% if product.image %}{{ product.image.url }}{% else %} http://dummyimage.com/300 {% endif %}">
                    </a>
                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                    {{ product.price }} руб.
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}